services:
  agent:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: kubeaid-agent:local
    container_name: kubeaid-agent
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HF_HOME=/workspace/models/embed
    volumes:
      - /usr/bin/kubectl:/usr/bin/kubectl:ro
      - /root/.kube/config:/root/.kube/config:ro
      - ./app:/workspace/app
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./config.yaml:/workspace/config.yaml
    ports:
      - "8000:8000"
