name: build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/kubeaid
  CONTEXT_DIR: kubeaid_offline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:offline-latest
            ${{ env.IMAGE_NAME }}:offline-${{ github.sha }}
